const DEFAULTS={cases:[],evidenceLedger:[],deployments:[],auditChain:[],activeCaseId:null,settings:{automaticVerdicts:false,automaticPublication:false}};
async function state(){return chrome.storage.local.get(DEFAULTS)}
async function sha256(text){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text||''));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function audit(action,payload={}){const s=await state(),prev=s.auditChain.at(-1)||null,timestamp=new Date().toISOString(),hash=await sha256(JSON.stringify({action,payload,timestamp,previousHash:prev?.hash||null}));s.auditChain.push({id:crypto.randomUUID(),timestamp,action,payload,previousHash:prev?.hash||null,hash});await chrome.storage.local.set(s);return hash}
async function createCase(query){const s=await state();const c={id:crypto.randomUUID(),createdAt:new Date().toISOString(),query:(query||'').trim(),status:'REVIEW_REQUIRED',confidence:0,evidenceIds:[],decision:null};s.cases.push(c);s.activeCaseId=c.id;await chrome.storage.local.set(s);await audit('CASE_CREATED',{caseId:c.id,query:c.query});return c}
async function captureTab(tabId,caseId){const response=await chrome.tabs.sendMessage(tabId,{type:'METATRUTH_CAPTURE_PAGE'});if(!response?.ok)throw new Error(response?.error||'Capture failed');const s=await state();const c=s.cases.find(x=>x.id===(caseId||s.activeCaseId));const material=JSON.stringify({claim:c?.query||'',url:response.url,title:response.title,excerpt:response.excerpt,capturedAt:response.capturedAt});const e={id:crypto.randomUUID(),claim:c?.query||'',source:{url:response.url,title:response.title,type:'page',retrieval:'user_capture'},capturedAt:response.capturedAt,excerpt:response.excerpt,contentHash:await sha256(material),status:'UNREVIEWED',assessment:null};s.evidenceLedger.push(e);if(c&&!c.evidenceIds.includes(e.id))c.evidenceIds.push(e.id);await chrome.storage.local.set(s);await audit('EVIDENCE_CAPTURED',{caseId:c?.id||null,evidenceId:e.id,sourceUrl:e.source.url});return e}
chrome.runtime.onInstalled.addListener(async()=>{const s=await state();await chrome.storage.local.set(s);await audit('EXTENSION_INSTALLED',{version:'0.4.0'})});
chrome.runtime.onMessage.addListener((m,sender,reply)=>{(async()=>{
 if(m.type==='CREATE_CASE')return reply(await createCase(m.query));
 if(m.type==='OPEN_META_SEARCHES'){const q=encodeURIComponent((m.query||'').trim());if(!q)throw new Error('Empty search');const urls=[`https://www.google.com/search?q=${q}`,`https://www.bing.com/search?q=${q}`,`https://duckduckgo.com/?q=${q}`];for(const url of urls)await chrome.tabs.create({url,active:false});await audit('META_SEARCH_OPENED',{query:m.query,engines:['Google','Bing','DuckDuckGo']});return reply({ok:true,count:urls.length});}
 if(m.type==='CAPTURE_ACTIVE_TAB'){const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab?.id)throw new Error('No active tab');return reply(await captureTab(tab.id,m.caseId));}
 if(m.type==='SET_ACTIVE_CASE'){const s=await state();s.activeCaseId=m.caseId||null;await chrome.storage.local.set(s);return reply({ok:true});}
 if(m.type==='JUDGE_CASE'){const s=await state(),c=s.cases.find(x=>x.id===m.caseId);if(!c)throw new Error('Case not found');const d=['approve','reject','needs_more_evidence'].includes(m.decision)?m.decision:'needs_more_evidence';c.status=d==='approve'?'APPROVED_FOR_AUDIT':d==='reject'?'REJECTED':'REVIEW_REQUIRED';c.confidence=Math.max(0,Math.min(100,Number(m.confidence)||0));c.decision={by:'Remedy',at:new Date().toISOString(),decision:d,note:m.note||'',evidenceReviewed:c.evidenceIds.length};await chrome.storage.local.set(s);await audit('JUDGE_DECISION',{caseId:c.id,decision:d,confidence:c.confidence,evidenceReviewed:c.evidenceIds.length});return reply(c);}
 if(m.type==='STAGE_DEPLOYMENT'){const s=await state(),d={id:crypto.randomUUID(),createdAt:new Date().toISOString(),version:'0.4.0',target:'staging',status:'STAGED',approvedCases:s.cases.filter(c=>c.status==='APPROVED_FOR_AUDIT').map(c=>c.id)};s.deployments.push(d);await chrome.storage.local.set(s);await audit('DEPLOYMENT_STAGED',{deploymentId:d.id,approvedCases:d.approvedCases.length});return reply(d);}
})().catch(e=>reply({error:String(e)}));return true});